function hf = buildInterface(tag)
scz = get(0, 'ScreenSize'); % Tamanho da tela

% Figura principal
hf = figure('Tag', tag,...
	'Toolbar','none',...
	'MenuBar','none',...
	'Units','pixels',...
	'OuterPosition', [0 0 scz(3)*0.6 scz(4)*0.8],...
	'Units','normalized',...
	'Resize','off',...
	'IntegerHandle','off',...
    'NumberTitle','off',...
    'HandleVisibility','callback',...
    'Name','Interface',...
    'CloseRequestFcn',@cb_closeMainWindow,...
    'Visible','off');
    
% Armazena todos os dados em hf
% guidata(hf, ad);

% Move para o centro e exibe a tela
movegui(hf, 'center');
set(hf, 'Visible', 'on');